[package]
name = "cobalt"
version = "0.1.0"
edition = "2024"

[dependencies]
egui-wgpu = "0.33.0"
env_logger = "0.11.8"
glam = { version = "0.30.9", features = ["zerocopy", "bytemuck", "approx"] }
glyphon = { git = "https://github.com/grovesNL/glyphon.git" } # support for wgpu 27 is only in git for now
hexasphere = "16.0.0"
log = "0.4.28"
pollster = "0.4.0"
wgpu = { version = "27", features = ["wgpu-core"] }
winit = "0.30"
